name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'server/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ecomm-api
  AZURE_WEBAPP_PACKAGE_PATH: './server'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json

    - name: Install dependencies
      run: |
        cd server
        npm ci --only=production

    - name: Create deployment artifact
      run: |
        cd server
        zip -r ../deploy.zip . -x "*.git*" "node_modules/.cache/*" "*.log"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deploy.zip

    - name: Health Check
      run: |
        sleep 30
        response=$(curl -s -o /dev/null -w "%{http_code}" https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/health)
        if [ $response -eq 200 ]; then
          echo "Deployment successful! Health check passed."
        else
          echo "Health check failed with status code: $response"
          exit 1
        fi
